trigger:
- cicd

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

stages:
- stage: Preview
  jobs:
  - job: Preview
    steps:
      - task: UseDotNet@2
        displayName: Install .NET Core
        inputs:
          version: 3.1.x

      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: 'build'
          projects: 'src/MudBlazor.sln'
          arguments: '--configuration $(buildConfiguration)'

      - task: DotNetCoreCLI@2
        displayName: Test
        inputs:
          command: 'test'
          projects: 'src/MudBlazor.UnitTests/MudBlazor.UnitTests.csproj'
          testRunTitle: 'UnitTest'

      - task: PowerShell@2
        displayName: Update Version
        inputs:
          targetType: 'inline'
          script: |
            $version = ([xml](Get-Content -Raw src/MudBlazor/MudBlazor.csproj))["Project"]["PropertyGroup"]["Version"].InnerText;
            $version += "-preview.$(Build.BuildNumber)";
            Write-Host $version;
            Write-Host "##vso[task.setvariable variable=version]$version";

      - task: DotNetCoreCLI@2
        displayName: Pack
        inputs:
          command: 'pack'
          configuration: '$(buildConfiguration)'
          packagesToPack: 'src/MudBlazor/MudBlazor.csproj'
          buildProperties: '-p:Version=$(version)'

- stage: Approval
  jobs:
  - deployment: Approval
    displayName: Approval
    environment: 'Approval'

- stage: Production
  jobs:
  - job: Production
    steps:
    - script: echo Testing on Windows!